#Fichero: makefile
#Este es el makefile del ejercicio 6 de la practica 4.
#Este makefile contruye una biblioteca "libMemoria.a",con "reservarMemoria.c" y "liberaMemoria.c".
#Construye el ejecutable "crucigrama.x" a partir de la biblioteca y los ficheros objeto.
#Permite eliminar los ficheros objeto generados.
